server:
  port: 8080
  servlet:
    context-path: /redis_demo

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/redis_demo"
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: nhatthaitn2003@gmail.com
    password: udxs gskd ozzt meyy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    flyway:
      enabled: true
      locations: classpath:/db/migration